name: nanome
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - biopython=1.78
  - blas=1.0
  - bleach=1.5.0
  - bwa=0.7.17
  - bwidget=1.9.11
  - bzip2=1.0.8
  - curl=7.76.1
  - deepmod=0.1.3
  - eigen=3.3.7
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.68.2
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=2.8.0
  - hdf5=1.8.18
  - intel-openmp=2021.2.0
  - jinja2=3.0.0
  - joblib=1.0.1
  - ld_impl_linux-64=2.33.1
  - libcurl=7.76.1
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - make=4.2.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - minimap2=2.17
  - nanopolish=0.13.2
  - ont-tombo=1.5.1
  - openssl=1.1.1k
  - packaging=20.9
  - pango=1.45.3
  - parallel=20210422
  - perl=5.26.2
  - pillow=8.2.0
  - pip=21.0.1
  - pycparser=2.20
  - pyfaidx=0.5.9.5
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysam=0.16.0.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2021.1
  - qt=5.9.7
  - readline=8.1
  - rpy2=3.3.6
  - samtools=1.12
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - seaborn=0.11.1
  - setuptools=52.0.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.35.4
  - tar=1.34
  - tensorboard=1.7.0
  - tensorflow=1.7.0
  - tensorflow-base=1.7.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.1
  - tqdm=4.60.0
  - typing_extensions=3.7.4.3
  - tzlocal=2.1
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - xz=5.2.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - numpy==1.18.5
  - pandas==1.1.5
  - patsy==0.5.1
  - statsmodels==0.12.2
  - ont-fast5-api==3.0
  - pybedtools=0.7.10
  - rocksdb
  - python-rocksdb
  - cython
  - openpyxl
  - nanocomp
  - pip:
    - ont-pyguppy-client-lib
    - deepsignal==0.1.8
    - fast5mod==1.0.5
#The conflict is caused by:
#    fast5mod 1.0.5 depends on ont-fast5-api==3.0.0
#    megalodon 2.3.4 depends on ont-fast5-api>=3.2
