name: nanome
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - python=3.6.13
  - biopython
  - bwa
  - h5py
  - jinja2
  - matplotlib
  - minimap2
  - parallel
  - pip
  - pysam
  - samtools
  - scikit-learn
  - scipy
  - seaborn
  - termcolor=1.1.0
  - tqdm=4.60.0
  - numpy
  - pandas
  - statsmodels
  - ont-fast5-api
  - pybedtools
  - rocksdb
  - python-rocksdb
  - cython
  - openpyxl
  - nanocomp
  - tensorboard=1.7.0
  - tensorflow=1.7.0
  - tensorflow-base=1.7.0
  - deepmod=0.1.3
  - megalodon=2.3.4
  - nanopolish=0.13.2
  - ont-tombo=1.5.1
  - pip:
    - deepsignal==0.1.8
    - fast5mod==1.0.5
    - ont-pyguppy-client-lib
